### ISSUE TITLE
Broken build in remix with cloudflare-workers. Use of import.meta.env.

### ISSUE THREAD

**Issue by mxck** [pmndrs/zustand#1639]
## Summary

I'm trying to use Zustand with Remix and Cloudflare Workers, but I'm running into an error. I also encountered the same error when using Jotai.

The error message I'm seeing is:
```
 ((_a = import.meta.env) == null ? void 0 : _a.MODE) !== "production" && console.warn(
                  ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
```

## Link to reproduction

Minimal remix setup from `npx create-remix@latest` and zustand.
https://github.com/mxck/remix-zustand-import-meta-error

## Check List

Please do not ask questions in issues.

- [x] I've already opened a [discussion](https://github.com/pmndrs/zustand/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

Please check this if you're filing an issue regarding TypeScript.

- [x] I've read the [typescript guide](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md), in particular that `create` is to be used as `create<T>()(...)` and not `create<T>(...)`.

**Comment by barelyhuman** [comment]
Is this with a default remix app? then I could reproduce to check , if it's certain versions that have a resolution issue the @mxck a reproduction repo from your side would help a ton

**Comment by mxck** [comment]
Yes, there is a reproduction demo in my first post.
https://github.com/mxck/remix-zustand-import-meta-error

**Comment by mxck** [comment]
And yes, it is exactly remix + cloudflare-workers. The [miniflare](https://github.com/cloudflare/miniflare) crashes.

**Comment by barelyhuman** [comment]
> And yes, it is exactly remix + cloudflare-workers. The [miniflare](https://github.com/cloudflare/miniflare) crashes.

My bad. I’ll check it out

**Comment by barelyhuman** [comment]
@mxck cool so I went through the repo, the problem is that the miniflare runs it all in CJS by default so you are better off expecting remix to output commonjs output so miniflare can execute it. 

The workaround for this for now is to just change your `remix.config.js` to have `serverModuleFormat` as `cjs`

your reproductions config would look something like this 

```diff
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  devServerBroadcastDelay: 1000,
  ignoredRouteFiles: ["**/.*"],
  server: "./server.js",
  serverConditions: ["worker"],
  serverDependenciesToBundle: "all",
  serverMainFields: ["browser", "module", "main"],
  serverMinify: true,
-  serverModuleFormat: "esm",
+  serverModuleFormat: "cjs",
  serverPlatform: "neutral",
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
};

```

If you really wish to have miniflare execute the build in `esm` then you can change your `package.json` script to execute it in esm format. 

the change would look something like this
```diff
```

**Comment by dai-shi** [comment]
@barelyhuman Thanks so much for helping this out!

**Comment by barelyhuman** [comment]
> @barelyhuman Thanks so much for helping this out!

I’m glad i could
