### ISSUE TITLE
Test improvements

### ISSUE THREAD

**Issue by barbogast** [pmndrs/zustand#414]
Working on #403 exposed a couple of potential improvements for the tests. I'm creating this issue to align which ones should actually be done, and how the changes should be grouped into PRs.

- [x] Reduce the usage of `any` in test files (#417)
  - Came up [here](https://github.com/pmndrs/zustand/pull/403#discussion_r642656923)
  - Would mean to add quite some type definitions to test files. Too much boilerplate? But types are nice, so I'm in favour of doing it.

- [x] Remove unnecessary mocks of `console.error` (#420)
  - Came up [here](https://github.com/pmndrs/zustand/pull/403#discussion_r642655833)
  - I guess the mocks are in for cases like [this one](https://github.com/pmndrs/zustand/blob/master/tests/persistSync.test.tsx#L146). Still can be removed where not used.

- [ ] ~~Rename [persistSync.test.tsx](https://github.com/pmndrs/zustand/blob/master/tests/persistSync.test.tsx) to `.ts` as it doesn't contain any JSX.~~

- [x] Rename [persist.test.tsx](https://github.com/pmndrs/zustand/blob/master/tests/persist.test.tsx) to `persistAsync.test.tsx` to be consistent. (#416)

- [x] Wrap tests in [persist.test.tsx](https://github.com/pmndrs/zustand/blob/master/tests/persist.test.tsx) into a `describe()` block to be consistent with [persistSync.test.tsx] (#416)(https://github.com/pmndrs/zustand/blob/master/tests/persistSync.test.tsx)
  - or should this be done with all test files?

- [x] [persist.test.tsx](https://github.com/pmndrs/zustand/blob/master/tests/persist.test.tsx): Make sure that `onRehydrateStorage` was not called with an error (#423)
  - I noticed that the tests will not fail on errors occurring during state initialisation as the error is only passed to `onRehydrateStorage`. Therefore each test needs to verify that `onRehydrateStorage` was called with `undefined`.
  - I already added this check to `persistSync.test.tsx` (see [example](https://github.com/pmndrs/zustand/blob/master/tests/persistSync.test.tsx#L129))

- [x] persist tests: Use `jest.fn()` to mock `onRehydrateStorage` instead of hand-crafting a spy (#423)
  - See [here](https://github.com/pmndrs/zustand/blob/master/tests/persistSync.test.tsx#L32) as example
  - No big deal, but my guess is that it would simplify the code, and make it more fail-safe

- [x] Add [this](https://github.com/pmndrs/zustand/blob/master/tests/persistSync.test.tsx#L145) test to the `persist.test.tsx` as well. (#430)

- [x] Add some structure to [basic.test.tsx](https://github.com/pmndrs/zustand/blob/master/tests/basic.test.tsx) (#424)
  - Right now it's 800 lines of `it()` calls 😅 
  - One way to add a bit of structure would be to have each `subscribe` and type-related tests be grouped under a separate `describe()` call within the same file.
  - ... or break up the file? Would need feedback on that one. 

 - [x] perstist*.test.tsx: Expand it('can persist state') by verifying that the persisted state is actually written to the storage (#431)
   - One of the more important scenarios, right?
 
- [x] split tests for `subscribe()` into multiple it() blocks (#427)

- [x] replace callbacks with spies for `subscribe()` tests (#429)

- [ ] ~~`persistAsync.test.tsx`: Move component `Counter` to top of file~~
  - Tried it, doesn't seem to be worth it.  Will skip.

- [x] Address inconsistency of arguments for `onRehydrateStorage` between sync and async (#437)
  - Follow-up of [this](https://github.com/pmndrs/zustand/pull/430#pullrequestreview-682429685)

- [x] Follow up on #431 (#436)
  - Implement also for async version.

- [ ] Add tests for outer `onRehydrateStorage` callback`
  - At the moment the tests only test the function returned by `onRehydrateStorage` which is called after rehydration, not the one that's called before rehydration.

I guess that all of those deserve separate PRs. So I'd just need to know which ones you want to be done, then I'd get going.

**Comment by dai-shi** [comment]
Thanks for opening this up!

> Rename persistSync.test.tsx to .ts as it doesn't contain any JSX.

I think we can leave it as it seems consistent `*.test.tsx`. We may eventually have JSX in the future.

> ... or break up the file? Would need feedback on that one.

Yeah, breaking up sounds good.

> I guess that all of those deserve separate PRs.

Yeah, smaller PRs are easier to review in general.

> So I'd just need to know which ones you want to be done, then I'd get going.

Overall seems good to me. For persist related tests, @AnatoleLucet can comment?

**Comment by AnatoleLucet** [comment]
Overall seems good to me too 👍

**Comment by barbogast** [comment]
@dai-shi @AnatoleLucet Or you fine with the current progress / approach / pace? I keep thinking that I'm nearly done and then new ideas for improvements pop up. Shall I continue as is? Or am I starting to over-engineer things?

Just looking for some quick, directional feedback here.

**Comment by dai-shi** [comment]
I'm fine. Having new ideas after some work is not surprising. Thanks for your contributions.

**Comment by dai-shi** [comment]
What's the latest status of this?

**Comment by barbogast** [comment]
Oh, right, the ticket is still open.

It can be closed as far as I'm concerned. One item is still open, but I'm doubtful that it's important enough and worth the effort.

Closing...
